name: testlens
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - pydantic>=2.0.0
  - colorama>=0.4.6
  - rich>=13.0.0
  - pytest>=7.0.0
  - pytest-asyncio>=0.23.0
  - python-dotenv>=1.0.0
  - black>=23.0.0
  - flake8>=6.0.0
  - mypy>=1.0.0
  - isort
  - pip:
    - browser-use>=0.2.0
    - asyncio-throttle>=1.0.0
    - pre-commit>=3.0.0
